@startuml
autonumber
hide footbox

actor "Courier" as U

participant ":System" as SYST

activate U
U -> SYST : Starts a delivery run
activate SYST
SYST --> U : informs of the success of the operation
deactivate SYST



deactivate U

@enduml