@startuml
skinparam classAttributeIconSize 0

package "UI" #DDDDDD {
class RegisterPharmacyUI{

}
}


package "Controller" #DDDDDD {
class RegisterPharmacyController{
+newPharmacy(managerName,email,password, nif, name,latitude,longitude,\nstreetName,doorNumber,postalCode,locality,country)
+registerPhamacy()
}

class ApplicationPOT
{
  +static getInstance()
  +getPlatform()
}

class UserSession
{
  +getCurrentSession()
}
}


package "Model" #DDDDDD {
class Platform {
  -String designation
  +getPharmacyReg()
  +getPharmacyManagerReg()
}
package "Registration" #DDDDDD {

   class PharmacyRegistration{
          +addPharmacy(name, pharmacyManager,latitude,longitude,streetName,doorNumber,postalCode,locality,country)
          +validatePharmacy()
          +registerPharmacy()
      }
   class PharmacyManagerRegistration{
             +addPharmacyManager(managerName,email,password, nif)
             +validatePharmacyManager()
         }
 }
}

package "Model" #DDDDDD {
abstract class User{
-String email
-String password
-String name
-Integer nif
}

class Pharmacy{
-   int id
-   String name
}

class PharmacyManager{
}

class Park{
-   int maxSlotsNumber
}

class ChargingSlot{
-   int id
-   float outputPower
}

class ParkingSlot{
-   int id
}

}


package "Data" #DDDDDD {
class DataHandler{
    +openConnection()
    +closeAll()
}
}

class PharmacyRegistration extends DataHandler
class PharmacyManagerRegistration extends DataHandler
class PharmacyManager extends User

RegisterPharmacyUI ..> RegisterPharmacyController
RegisterPharmacyController ..> Platform
RegisterPharmacyController ..> ApplicationPOT
RegisterPharmacyController ..> UserSession
Platform "1" --> "1" PharmacyRegistration : has
PharmacyRegistration "1" --> "*" Pharmacy : manages
PharmacyManagerRegistration "1" --> "*" PharmacyManager : manages

Pharmacy "1" -- "1" PharmacyManager : has >
Pharmacy "1" -- "1" Park : has >
Park "1" -- "1" ChargingSlot : has >
Park "1" -- "1" ParkingSlot : has >

@enduml