@startuml
skinparam classAttributeIconSize 0


package "Controller" #DDDDDD {
class ApplicationPOT
{
  +static getInstance()
  +getPlatform()
}
}


package "UI" #DDDDDD {
class RegisterClientUI{

}
}


package "Controller" #DDDDDD {
class RegisterClientController{
+validateInput(name,email,password,latitude,longitude,streetName,\ndoorNumber,postalCode,locality,country,creditCardNr,validityDate,CCV)
+registerNewClient(name,nif,email,password,latitude,longitude,streetName,\ndoorNumber,postalCode,locality,country,creditCardNr,validityDate,CCV)
}
}


package "Model" #DDDDDD {
class Platform {
  -String designation
  +getClientReg()
}
package "Registration" #DDDDDD {
 class ClientRegistration{
 +registerNewClient(name,nif,email,password,latitude,longitude,streetName,\ndoorNumber,postalCode,locality,country,creditCardNr,validityDate,CCV)
 +addClientToDB(client)
 }
 }
}




package "Model" #DDDDDD {
abstract class User{
-String email
-String password
+User(email,password)
}

class Client extends User

class Client{
-String name;
-Address address;
-Integer creditCardNr;
-String validityDate;
-Integer CCV;
+Client(name,nif,email,password,latitude,longitude,streetName,doorNumber,postalCode,locality,country,
                        creditCardNr,validityDate,CCV)
}

class Address{
-Integer id
-float latitude
-float longitude
-String streetName
-String doorNumber
-String postalCode
-String locality
-String country
+Address(latitude,longitude,streetName,doorNumber,postalCode,locality,country)
}

class CreditCard{
-Integer m_creditCardNr;
-String m_validityDate;
-Integer m_CCV;
+CreditCard(creditCardNr,validityDate,CCV)
}

}


package "Data" #DDDDDD {
class DataHandler{
+openConnection()
+closeAll()
}

}


RegisterClientUI ..> RegisterClientController
RegisterClientController ..> Platform
RegisterClientController ..> ApplicationPOT
Platform "1" --> "1" ClientRegistration : has
ClientRegistration "1" --> "*" Client : creates
class ClientRegistration extends DataHandler
Client "1" --> "1" Address : has
Client "*" --> "*" CreditCard : has

@enduml