@startuml
skinparam classAttributeIconSize 0
hide methods
left to right direction

class Platform {
-   String designation
}

class Client{
-String name
-Address address
-String gpsLocation
-Integer creditCardNr
-Integer validityDate
-Integer CCV
}

abstract class User{
-String email
-String password
}

class Client extends User


Client "1" -- "1" Client : registers
Platform "1" -- "*" Client : has registered >
Platform "1" -- "*" User : has registered >
@enduml