@startuml
autonumber
hide footbox

actor "Client" as U

participant "RegisterClientUI" as UI
participant "RegisterClientController" as CTRL
participant "ApplicationPOT" as _APP
participant "app\n:ApplicationPOT" as APP
participant "plat\n:Platform" as PLAT
participant "clientReg\n:ClientRegistration" as UREG

participant "client\n:Client" as USER
participant Address as ADD

participant "DataHandler" as DH

activate U

U -> UI : Engages the register feature/button
activate UI

UI --> U : Asks for all the information required \nfor the register (i.e. name,email,password,address,\ngpsLocation,creditCardNr,validityDate,CCV)


deactivate UI
U -> UI : Fills all the information required


activate UI


UI --> U : Validates, presents the data and asks for a confirmation

deactivate UI
U -> UI : Confirms
activate UI
UI -> CTRL : registerNewUser(name,email,password,latitude,longitude,streetName,\ndoorNumber,postalCode,locality,country,creditCardNr,validityDate,CCV)
activate CTRL
CTRL -> CTRL : validateInput(name,email,password,latitude,longitude,streetName,\ndoorNumber,postalCode,locality,country,creditCardNr,validityDate,CCV)

opt if all the information given as input has a valid format

CTRL -> _APP: app = getInstance()
activate _APP
deactivate _APP

CTRL -> APP: plat = getPlaform()
activate APP
deactivate APP
CTRL -> PLAT : clientReg = getClientReg()
activate PLAT
deactivate PLAT

CTRL -> UREG : registerNewClient(name,email,password,latitude,longitude,streetName,\ndoorNumber,postalCode,locality,country,creditCardNr,validityDate,CCV)
activate UREG


UREG -> USER** : create(name,email,password,latitude,longitude,streetName,\ndoorNumber,postalCode,locality,country,creditCardNr,validityDate,CCV)
activate USER
USER -> ADD** : create(latitude,longitude,streetName,doorNumber,postalCode,locality,country)
deactivate USER




UREG -> UREG : addClientToDB(client)
ref over UREG
SD_CONNECTIONS
end ref


deactivate UREG



deactivate CTRL

UI --> U : Informs about the success of the operation

end opt



deactivate UI
deactivate U

@enduml