@startuml
skinparam classAttributeIconSize 0
hide methods
left to right direction

class Platform {
-   String designation
}

class Client{
-String credits
}

abstract class User{
-Integer id
-String email
-String password
-Integer nif
-String name
}

class Address{
-Integer id
-float latitude
-float longitude
-String streetName
-String doorNumber
-String postalCode
-String locality
-String country
}

class CreditCard{
-Double creditCardNr;
-String validityDate;
-Integer CCV;
+CreditCard(creditCardNr,validityDate,CCV)
}

class Client extends User


Client "1" -- "1" Client : registers
Client "1" -- "1" Address : has
Client "*" -- "*" CreditCard : has
Platform "1" -- "*" Client : has registered >
Platform "1" -- "*" User : has registered >
@enduml