@startuml
skinparam classAttributeIconSize 0
hide methods
left to right direction

class Platform {
-   String designation
}

class Client{
-String name;
-Address address;
-Integer creditCardNr;
-String validityDate;
-Integer CCV;
}

abstract class User{
-String email
-String password
}

class Address{
-float latitude
-float longitude
-String streetName
-String doorNumber
-String postalCode
-String locality
-String country
}

class Client extends User


Client "1" -- "1" Client : registers
Client "1" -- "1" Address : has
Platform "1" -- "*" Client : has registered >
Platform "1" -- "*" User : has registered >
@enduml