@startuml
autonumber
hide footbox

actor "Admin" as U

participant "RegisterProductUI" as UI
participant "RegisterProductController" as CTRL
participant "ProductService" as SER
participant "ProductDB" as DB
participant "product\n:Product" as PROD

activate U
U -> UI : Engages the register product feature/button
activate UI
UI --> U : Asks for all the information required for the register (id, name, description, unitaryPrice, unitaryWeight)
deactivate UI
U -> UI : Fills all the information required
activate UI
UI -> CTRL : registerProduct(strName, strDescription, fltUnitaryPrice, fltUnitaryWeight);
activate CTRL
CTRL -> SER : registerProduct(strName, strDescription, fltUnitaryPrice, fltUnitaryWeight);
activate SER
SER -> SER : validateInput(strName, strDescription, fltUnitaryPrice, fltUnitaryWeight)
opt if all the information given as input has a valid format
SER -> PROD** : create(strName, strDescription, fltUnitaryPrice, fltUnitaryWeight)
SER -> DB : addProductToDB(product)
activate DB
deactivate DB
ref over DB
SD_CONNECTIONS
end ref
deactivate SER
deactivate CTRL
deactivate CTRL
UI --> U : Validates all the information, informing of the success of the operation
else if any information does not have a valid format
UI -> U : Informs that the operation was not successful
deactivate UI
deactivate U
end opt

@enduml