@startuml
skinparam classAttributeIconSize 0

class PotApplication
{
  +static getInstance()
  +getPlatform()
}

class CalculateMostEfficientPahtUI{

}

class CalculateMostEfficientPahtController{
+getShortestPath()
}

class Platform {
  -String designation
  +DeliveryRegistry getDelReg()
}
class DeliveryRegistry{
+getShortestPath(Address a, Address b)
}



CalculateMostEfficientPahtUI ..> CalculateMostEfficientPahtController
CalculateMostEfficientPahtController ..> Platform
CalculateMostEfficientPahtController ..> PotApplication
Platform "1" --> "1" DeliveryRegistry : has
@enduml