@startuml
autonumber
hide footbox

actor "Pharmacy Manager" as PM
participant ":System" as SYST

activate PM

PM -> SYST : initiates the process
activate SYST
SYST --> PM : shows the product list
deactivate SYST

PM -> SYST : selects the product
activate SYST
SYST --> PM : asks for the stock for said product
deactivate SYST

PM -> SYST : introduces the stock
activate SYST
SYST --> PM : validates and presents the information
deactivate SYST

PM -> SYST : confirms
activate SYST
SYST --> PM : informs of the success of the operation
deactivate SYST

deactivate PM

@enduml