@startuml
autonumber
hide footbox

actor "Pharmacy Manager" as PHARMAN

participant ":System" as SYST

activate PHARMAN

PHARMAN -> SYST : Sends a request regarding the update of an electric scooter's data
activate SYST
SYST --> PHARMAN : Shows the list of eletric scooters and asks to choose one
deactivate SYST
PHARMAN -> SYST : Chooses the eletric scooter
activate SYST
SYST -> PHARMAN : Shows the information about the scooter, asking to update
deactivate SYST

PHARMAN -> SYST : Updates the information
activate SYST
SYST -> PHARMAN : Validates all the information, informing of the success of the operation
deactivate SYST

deactivate PHARMAN

@enduml