@startuml
autonumber
actor "Courier" as COURIER

participant ":SeeSuitableVehicleUI" as UI
participant ":SeeSuitableVehicleController" as CTRL
participant "ApplicationPot" as PA
participant "app \n:ApplicationPot" as APA
participant "session \n:UserSession" as US
participant "scooterReg \n:VehicleService" as RF
participant "vehicleDB \n:VehicleDB" as SDB
participant "scooter \n:Scooter" as CS
participant "drone \n:Drone" as DR

activate COURIER

COURIER -> UI :  wants to see the scooters available
activate UI
UI -> CTRL : vehicle = getSuitableVehicle()
activate CTRL
CTRL -> RF : create()
activate RF
RF -> SDB : create()
activate SDB
deactivate RF
deactivate SDB
CTRL -> PA : app = getInstance()
activate PA
deactivate PA
CTRL -> APA : session = getCurrentSession()
activate APA
deactivate APA
CTRL -> US : email = getCurrentUserEmail()
activate US
deactivate US
CTRL -> RF : scooter = getSuitableVehicle(distance,email)
activate RF
RF -> SDB : scooter = getSuitableScooter(distance,email)
activate SDB
deactivate SDB
RF -> SDB : drone = getSuitableDrone(distance,email)
activate SDB
deactivate SDB
deactivate RF
deactivate CTRL


UI -> COURIER : presents the information about the available scooters
deactivate UI

deactivate COURIER

@enduml
