@startuml
autonumber
participant ":MakeAPharmacyTransferController" as CTRL
participant "pharmServ \n:PharmacyService" as PS
participant "pharamcyDB\n:PharmacyDB" as PDB
participant "pharmacyTransfer\n:PharmacyTransfer" as PT

[o-> CTRL : getStockFromAnotherPharamacy\n(order, product, quantity)
activate CTRL
CTRL -> PS** : create()
CTRL -> PDB** : create()
CTRL -> PS : nearbyPharamcy = getClosestPharmacyWithStock\n(pharmacy, product, quantity)
activate PS
PS -> PDB : nearbyPharamcy = getClosestPharmacyWithStock\n(pharmacy, product, quantity)
activate PDB
ref over PDB
SD_CONNECTIONS
end ref
deactivate PDB
deactivate PS

CTRL -> PS : newPharamacyTransfer\n(order, product, quantity, nearbyPharamcy)
activate PS
PS -> PT** : create(order, product, quantity, nearbyPharamcy)
deactivate PS

CTRL -> PS : registersPharmacyTransfer(pharmacyTransfer)
activate PS
PS -> PDB : registersPharmacyTransfer(pharmacyTransfer)
activate PDB
ref over PDB
SD_CONNECTIONS
end ref
deactivate PDB
deactivate PS
deactivate CTRL

@enduml
