@startuml
autonumber
hide footbox

actor "Courier" as COUR

participant "KnowDeliveryUI" as UI
participant "KnowDeliveryController" as CTRL

activate COUR

COUR -> UI : Sends a request regarding what delivery will be done
activate UI
UI -> COUR : Requests the information about the Courier (id)
deactivate UI

COUR -> UI : Introduces the required information
activate UI
UI -> CTRL : getCourierById(id)
activate CTRL



@enduml