@startuml
skinparam classAttributeIconSize 0

class PotApplication
{
  +static getInstance()
  +getCurrentSession()
}

class UserSession
{
  +getEmailUser()
}
class KnowDeliveryUI{

}

class KnowDeliveryController{
+getCourierInfo()
+getPlatform()
+getOrderByCour()
}

class Platform {
  -String designation
  +CourierRegistry getCourReg()
  +OrdersRegistry getOrdReg()
}
class CourierRegistry{
+getCourByEmail(email)
}

class OrdersRegistry{
+getOrdersList()
}

class OrdersList{
+getOrderByCourier(cour)
+hasOrder(cour)
+getOrderByCour(cour)
}

KnowDeliveryUI ..> KnowDeliveryController
KnowDeliveryController ..> Platform
KnowDeliveryController ..> PotApplication
KnowDeliveryController ..> UserSession
Platform "1" --> "1" CourierRegistry : has
Platform "1" --> "1" OrdersRegistry : has
OrdersRegistry "1" --> "1" OrdersList : has

@enduml