@startuml
skinparam classAttributeIconSize 0
hide methods
left to right direction

class Platform {
-   String designation
}


abstract class User{
-String email
-String password
}




Platform "1" -- "*" User : has registered >
@enduml