@startuml
autonumber
hide footbox

participant ":System" as SYST



SYST -> SYST : initiates the process of calculating\nthe shortest path between two\naddresses passing by intermediate addresses
activate SYST
deactivate SYST

@enduml