@startuml
skinparam classAttributeIconSize 0


package "UI" #DDDDDD {
class CalculateMostEfficientPahtUI{

}
}
package "Controller" #DDDDDD {
class CalculateMostEfficientPahtController{
+getShortestPath(startAddress, endAddress, deliveryPoints)
}
class ApplicationPOT
{
  +static getInstance()
  +getWorldMap()
}
class UserSession
{
  +getCurrentUserEmail()
}
}
package "Model" #DDDDDD {
 class WorldMap {
 +calculateMostEfficientPath(startAddress, endAddress, deliveryPoints)
 }

class Address{
-Integer id
-Double latitude
-Double longitude
-String streetName
-String doorNumber
-String postalCode
-String locality
-String country
+Address(latitude,longitude,streetName,doorNumber,postalCode,locality,country)
}

}
package "Data" #DDDDDD {
class DataHandler{
+openConnection()
+closeAll()
}


 database database{
 }
 }


CalculateMostEfficientPahtController ..> UserSession
CalculateMostEfficientPahtUI ..> CalculateMostEfficientPahtController
CalculateMostEfficientPahtController ..> ApplicationPOT
CalculateMostEfficientPahtController ..> DeliveryRunService
ApplicationPOT "1" ..> "1" WorldMap
database ->Address : has


@enduml