@startuml
autonumber
actor "Administrator" as ADMIN

participant ":RegisterPharmacyUI" as UI
participant ":RegisterPharmacyController" as CTRL
participant "PotApplication" as PA
participant "app \n:PotApplication" as APA
participant "session \n:UserSession" as US
participant "plat \n:Platform" as PLAT
participant "pharmReg \n:PharmacyRegistration" as PR
participant "pharmacy: Pharmacy" as PH



activate ADMIN

ADMIN -> UI : initiates the registration of a pharmacy
activate UI
UI -> ADMIN : asks for the required data for the pharmacy, as well as its Manager's data
deactivate UI

ADMIN -> UI : inserts the required data
activate UI
UI -> CTRL : newPharmacy(name,email, nif, iban)
activate CTRL
CTRL -> PA : app = getInstance()
activate PA
deactivate PA
CTRL -> APA : plat = getPlatform()
activate APA
deactivate APA
CTRL -> PLAT : pharmReg = getPharmacyReg()
activate PLAT
deactivate PLAT
CTRL -> PR : newPharmacy(name, nif, email, iban)
activate PR
PR -> PH ** : create(name, email, password, nif, iban)
deactivate PR
deactivate CTRL


UI -> ADMIN : validates, presents the information and asks for confirmation
deactivate UI

ADMIN -> UI : confirms
activate UI
UI -> CTRL : registersCourier()
activate CTRL
CTRL -> PR : registersCourier(courier)
activate PR
ref over PR
SD_CONNECTIONS
end ref
deactivate PR
UI -> ADMIN : informs the success of the operation
deactivate PR
deactivate CTRL
deactivate UI

deactivate ADMIN

@enduml
