@startuml
skinparam classAttributeIconSize 0
hide methods
left to right direction

class Platform {
-   String designation
}

class Pharmacy{
-   int id
-   String name
}

class User{
-   String name
-   String name
-   String email
-   String password
}

class PharmacyManager{
}

class Park{
-   int maxSlotsNumber
}

class ChargingSlot{
-   int id
-   float outputPower
}

class ParkingSlot{
-   int id
}

Platform "1" -- "*" Pharmacy : has registered >
Platform "1" -- "*" PharmacyManager : has registered >
PharmacyManager "0..1" -- "1" User: acts as >
Pharmacy "1" -- "1" PharmacyManager : has >
Pharmacy "1" -- "1" Park : has >
Park "1" -- "1" ChargingSlot : has >
Park "1" -- "1" ParkingSlot : has >
@enduml