@startuml
autonumber
hide footbox

actor "Pharmacy Manager" as PHARMAN

participant ":System" as SYST

activate PHARMAN

PHARMAN -> SYST : Sends a request regarding the remove of an electric scooter
activate SYST
SYST --> PHARMAN : Shows the list of eletric scooters and asks to choose one
deactivate SYST
PHARMAN -> SYST : Chooses the eletric scooter
activate SYST
SYST -> PHARMAN : Removes the eletric scooter
deactivate SYST

deactivate PHARMAN

@enduml