@startuml
actor "Admin" as ADMIN

participant ":System" as SYST

activate ADMIN
ADMIN -> SYST : Requests the vehicle maximum payload
activate SYST
SYST --> ADMIN : Asks for the vehicle ID
deactivate SYST

ADMIN -> SYST : Fills the information
activate SYST

SYST --> ADMIN : Validates and presents the vehicle maximum payload.
deactivate SYST
@enduml