@startuml
autonumber
hide footbox

actor "Admin" as ADMIN

participant ":VehiclePayloadUI" as UI
participant ":VehiclePayloadController" as CTRL
participant "vehicleService\n:VehicleService" as VS
participant "vehicleDB\n:VehicleDB" as VDB

activate ADMIN
ADMIN -> UI : Requests the vehicle payload
activate UI
UI-> ADMIN : Asks for the vehicle ID
deactivate UI
ADMIN -> UI : Fills the information
activate UI
UI -> CTRL : getVehiclePayload(vehicleId)
activate CTRL
CTRL -> VS* : create()
activate VS
VS -> VDB* : create()
deactivate VS
CTRL -> VS : payload = getVehiclePayload(vehicleId)
activate VS
VS -> VDB : payload = getVehiclePayload(vehicleId)
activate VDB
ref over VDB : SD_CONNECTIONS
deactivate VDB
deactivate VS
deactivate CTRL
opt payload !=null
UI -> ADMIN : Validates and presents the vehicle payload.
end opt
UI -> ADMIN : Informs the admin that the vehicle id\ninserted is invalid.
deactivate UI

@enduml