@startuml
skinparam classAttributeIconSize 0

database Database {
}

package "UI" #DDDDDD {
class VehiclePayloadUI{
}
}

package "Controller" #DDDDDD {
class VehiclePayloadController{
+getVehiclePayload(vehicleId)
}
}


package "Model" #DDDDDD {
 package "Service" #DDDDDD {

  class VehicleService{
      +VehicleService()
      +getVehiclePayload(vehicleId)
   }

}

package "Model" #DDDDDD {

class Vehicle{
  -int id
  -String vehicleType
  -float potency
  -float weight
  -float maxPayload
  -String charngingStatus
}

}


package "Data" #DDDDDD {
class DataHandler{
    +openConnection()
    +closeAll()
}
class VehicleDB{
     +VehicleDB()
     +getVehiclePayload(vehicleId)
 }

}

class VehicleDB extends DataHandler

VehiclePayloadUI ..> VehiclePayloadController
VehiclePayloadController ..> VehicleService
Database "1" --> "1" VehicleDB : manages
VehicleService "1" --> "*" Vehicle : manage services of
Database "1" -- "*" Vehicle : has registered >

@enduml