INSERT INTO "User"(EMAIL,PASSWORD,NIF,NAME) VALUES('user1@gmail.com','5f4dcc3b5aa765d61d8327deb882cf99',123456789,'user 1');

INSERT INTO ADMINISTRATOR(USERID) VALUES (1);

INSERT INTO VEHICLETYPE(DESIGNATION) VALUES('Scooter');
INSERT INTO VEHICLETYPE(DESIGNATION) VALUES('Drone');

INSERT INTO ORDERSTATUS(DESIGNATION) VALUES ('Transfering Products');
INSERT INTO ORDERSTATUS(DESIGNATION) VALUES ('Ordered');
INSERT INTO ORDERSTATUS(DESIGNATION) VALUES ('Delivering');
INSERT INTO ORDERSTATUS(DESIGNATION) VALUES ('Delivered');
INSERT INTO ORDERSTATUS(DESIGNATION) VALUES ('Cancelled');

INSERT INTO DELIVERYSTATUS(DESIGNATION) VALUES ('Idle');
INSERT INTO DELIVERYSTATUS(DESIGNATION) VALUES ('InProgress');
INSERT INTO DELIVERYSTATUS(DESIGNATION) VALUES ('Finished');

commit;