DELETE FROM PATH WHERE ADDRESSIDA <100;

DELETE FROM CHARGINGSLOT WHERE ID < 100;

DELETE FROM PARK WHERE PHARMACYID < 100;

DELETE FROM DELIVERYSTATUS WHERE DESIGNATION != '';

DELETE FROM ORDERSTATUS WHERE DESIGNATION != '';

DELETE FROM CREDITCARDCLIENT WHERE CREDITCARDCLIENT.CREDITCARDNR < 100;

DELETE FROM CREDITCARD WHERE CREDITCARDNR < 100;

DELETE FROM DELIVERY WHERE ORDERID < 100;

DELETE FROM DELIVERYRUN WHERE ID < 100;

DELETE FROM DELIVERYSTATUS WHERE DESIGNATION != '';

DELETE FROM SCOOTER WHERE ID < 100;

DELETE FROM CHARGINGSTATUS WHERE DESIGNATION != '';

DELETE FROM COURIER WHERE COURIER.USERID < 100;

DELETE FROM ORDERPRODUCT WHERE ORDERID < 100;

DELETE FROM PHARMACYPRODUCT WHERE PHARMACYID < 100;

DELETE FROM PRODUCT WHERE ID < 100;

DELETE FROM "Order" WHERE ID < 100;

DELETE FROM ORDERSTATUS WHERE DESIGNATION != '';

DELETE FROM CLIENT WHERE USERID < 100;

DELETE FROM ADMINISTRATOR WHERE USERID < 100;

DELETE FROM PHARMACY WHERE ID < 100;

DELETE FROM PHARMACYMANAGER WHERE USERID < 100;

DELETE FROM "User" WHERE ID < 100;

DELETE FROM ADDRESS WHERE ID < 100;