@startuml
skinparam classAttributeIconSize 0

package "UI" #DDDDDD {
class MakeAnOrderUI{

}
}


package "Controller" #DDDDDD {
class MakeAnOrderController{
+registerNewUser(name,email,password,address,gpsLocation,creditCardNr,validityDate,CCV)
}

class ApplicationPOT
{
  +static getInstance()
  +getPlatform()
}

class UserSession
{
  +getCurrentSession()
}
}


package "Model" #DDDDDD {
class Platform {
  -String designation
  +getClientReg()
  +getProductReg()
  +getOrderReg()
}
package "Registration" #DDDDDD {

  class PharmacyRegistration{
       +addPharmacy(address, amount, additionalFee, dateOrder, description, mapProducts, client)
       +validateOrder(pharmacy)
   }
 }
}

package "Model" #DDDDDD {
abstract class User{
-String email
-String password
-String name
}

class Pharmacy{
-   int id
-   String name
}

class PharmacyManager{
}

class Park{
-   int maxSlotsNumber
}

class ChargingSlot{
-   int id
-   float outputPower
}

class ParkingSlot{
-   int id
}

}


package "Data" #DDDDDD {
class DataHandler{
    +openConnection()
    +closeAll()
}
}

class PharmacyRegistration extends DataHandler

class PharmacyManager extends User

MakeAnOrderUI ..> MakeAnOrderController
MakeAnOrderController ..> Platform
MakeAnOrderController ..> ApplicationPOT
MakeAnOrderController ..> UserSession
Platform "1" --> "1" PharmacyRegistration : has
PharmacyRegistration "1" --> "*" Pharmacy : manages

Platform "1" -- "*" Pharmacy : has registered >
Platform "1" -- "*" PharmacyManager : has registered >
Pharmacy "1" -- "1" PharmacyManager : has >
Pharmacy "1" -- "1" Park : has >
Park "1" -- "1" ChargingSlot : has >
Park "1" -- "1" ParkingSlot : has >

@enduml