@startuml
skinparam classAttributeIconSize 0

class PotApplication
{
  +static getInstance()
  +getPlatform()
  +getCurrentSession()
}
class Database{
   +static executeQuery(query)
   +openConnection()
   +closeAll()
}
class UserSession
{
  +getUserEmail()
}
class KnowDeliveryUI{

}

class KnowDeliveryController{
+getCourierInfo()
+getOrderByCour()
}

class Platform {
  -String designation
  +CourierRegistry getCourReg()
  +OrdersRegistry getOrdReg()
}
class CourierRegistry{
+getCourByEmail(email)
}

class OrdersRegistry{
+getOrdersList()
}


KnowDeliveryUI ..> KnowDeliveryController
KnowDeliveryController ..> Platform
KnowDeliveryController ..> PotApplication
KnowDeliveryController ..> UserSession
Platform "1" --> "1" CourierRegistry : has
Platform "1" --> "1" OrdersRegistry : has
CourierRegistry "1" --> "1" Database : connects to
OrdersRegistry "1" --> "1" Database : connects to

@enduml