@startuml
autonumber
hide footbox

participant "droneMovementController\n:DroneMovementController" as CTRL
participant "droneServ\n:DroneService" as DS
participant "droneDB\n:DroneDB" as DDB
participant "pathInfo\n:Pair<LinkedList<Address>, Double>" as PI
participant "drone\n:Drone" as D


[o-> CTRL : moveDrone(pathInfo, drone)
activate CTRL
CTRL -> DS* : create()
CTRL -> DS : checkEnergy(distance, drone)
activate DS
DS -> DS : hasEnoughEnergy(energy, distance)
opt checkEnergy == true
deactivate DS
CTRL -> DS: startDelivery
activate DS
deactivate DS
end opt
deactivate CTRL
@enduml