@startuml
autonumber
actor "Administrator" as ADMIN

participant ":RegisterPharmacyUI" as UI
participant ":RegisterPharmacyController" as CTRL
participant "PotApplication" as PA
participant "app \n:PotApplication" as APA
participant "session \n:UserSession" as US
participant "plat \n:Platform" as PLAT
participant "pharmManReg \n:PharmacyManagerRegistration" as PMR
participant "pharmReg \n:PharmacyRegistration" as PR
participant "pharmacy: Pharmacy" as PH
participant "address: Address" as A
participant "pharmacyManager: PharmacyManager" as PM



activate ADMIN

ADMIN -> UI : initiates the registration of a pharmacy
activate UI
UI -> ADMIN : asks for the required data for the pharmacy, as well as its Manager's data
deactivate UI

ADMIN -> UI : inserts the required data
activate UI
UI -> CTRL : newPharmacy(managerName,email,password, nif, name,latitude,longitude,\nstreetName,doorNumber,postalCode,locality,country)
activate CTRL
CTRL -> PA : app = getInstance()
activate PA
deactivate PA
CTRL -> APA : plat = getPlatform()
activate APA
deactivate APA
CTRL -> PLAT : pharmManReg = getPharmacyManagerReg()
activate PLAT
deactivate PLAT
CTRL -> PMR : pharmacyManager = newPharmacyManger(managerName,email,password, nif)
activate PMR
PMR -> PM ** : create(managerName,email,password, nif)
PMR -> PMR : validatePharmacyManager()
ref over PMR
SD_CONNECTIONS
end ref
deactivate PMR
CTRL -> PLAT : pharmReg = getPharmacyReg()
activate PLAT
deactivate PLAT
CTRL -> PR : pharmacy= newPharmacy(name, pharmacyManager,latitude,longitude,streetName,doorNumber,\npostalCode,locality,country)
activate PR
PR -> PH ** : create(name, pharmacyManager, latitude,longitude,streetName,doorNumber,\npostalCode,locality,country)
PR -> A ** : create(latitude,longitude,streetName,doorNumber,\npostalCode,locality,country)
PR -> PR : validatePharmacy()
ref over PR
SD_CONNECTIONS
end ref
deactivate PR
deactivate CTRL


UI -> ADMIN : validates, presents the information and asks for confirmation
deactivate UI

ADMIN -> UI : confirms
activate UI
UI -> CTRL : registersCourier()
activate CTRL
CTRL -> PR : registersPharmacy(pharmacy)
activate PR
ref over PR
SD_CONNECTIONS
end ref
deactivate PR
UI -> ADMIN : informs the success of the operation
deactivate PR
deactivate CTRL
deactivate UI

deactivate ADMIN

@enduml
