@startuml
autonumber
hide footbox

actor "Client" as U

participant ":System" as SYST

activate U

U -> SYST : Engages the register feature/button
activate SYST
SYST --> U : Asks for all the information required \nfor the register (i.e. name,nif,email,password,latitude,longitude,altitude,\nstreetName,doorNumber,postalCode,locality,country,creditCardNr,validityDate,\nCCV)
deactivate SYST

U -> SYST : Fills all the information required
activate SYST
SYST --> U : Presents the data and asks for a confirmation
deactivate SYST

U -> SYST : Confirms
activate SYST
SYST --> U : Validates and informs about the success of the operation
deactivate SYST

deactivate U

@enduml