@startuml
autonumber
hide footbox

actor "Admin" as ADM

participant ":System" as SYST

activate ADM

ADM -> SYST : Initiates the registration of a delivery run
activate SYST

SYST --> ADM: Asks for a list of orders

deactivate SYST



ADM -> SYST : Gives an order id list
activate SYST


SYST --> ADM : Registers the delivery run and informs\nabout the success of the operation
deactivate SYST

deactivate ADM

@enduml