@startuml
autonumber
hide footbox

actor "Client" as U

participant "LogoutUI" as UI
participant "LogoutController" as CTRL


participant "session\n:UserSession" as SES
participant "ApplicationPOT" as _APP
participant "app\n:ApplicationPOT" as APP
participant "user\n:User" as USER


activate U

U -> UI : Engages the logout feature/button
activate UI
UI --> U : Asks for confirmation
deactivate UI

U -> UI : Confirms
activate UI

UI -> CTRL : logout()
activate CTRL
CTRL -> _APP: app = getInstance()
activate _APP
deactivate _APP


CTRL -> SES** : create()
activate SES
deactivate SES
SES -> _APP : clearCurrentSession()


activate _APP
deactivate _APP

deactivate CTRL

UI --> U : Deallocates the current session from the user and\ninforms about the success of the operation
deactivate UI

@enduml