@startuml
autonumber
hide footbox

actor "Courier" as COUR

participant "CalculateMostEfficientPahtUI" as UI
participant "CalculateMostEfficientPahtController" as CTRL
participant "ApplicationPOT" as _APP
participant "app\n:ApplicationPOT" as APP
participant "session\n:UserSession" as SESSION
participant "drService\n:DeliveryRunService" as DRS
participant "oDeliveryRunDB\n:DeliveryRunDB" as DRDB
participant "oDeliveryDB\n:DeliveryDB" as DDB
participant "list\nList<Address>" as LIST

activate COUR

COUR -> UI : Sends a request regarding what is the shortest \nand efficient path to the destiny
activate UI
UI -> CTRL : getShortestPath()
activate CTRL
CTRL -> _APP: app = getInstance()
activate _APP
deactivate _APP

CTRL -> APP: session = getCurrentSession()
activate APP
deactivate APP

CTRL -> SESSION : email = getCurrentUserEmail()
activate SESSION
deactivate SESSION

CTRL ->DRS* : create()
activate DRS
DRS -> DRDB* : create()
deactivate DRS
CTRL -> DRS : list = getAddressesByDeliveryRunId(email)
activate DRS
DRS -> DRDB : list = getAddressesByDeliveryRunId(email)
activate DRDB
ref over DRDB : SD_CONNECTIONS
deactivate DRDB
deactivate DRS
opt list !=null
CTRL -> DRS : calculateMostEfficientPath(addressA, addressB, list)
activate DRS
DRS -> DDB* : create()
DRS -> DDB : calculateMostEfficientPath(addressA, addressB, list)
activate DDB
ref over DDB : SD_CONNECTIONS
deactivate DDB
deactivate DRS
end opt
deactivate CTRL
UI -> COUR : Shows the shortest and most efficient path, \ninforming of the success of the operation.
deactivate UI
deactivate COUR

@enduml