@startuml
autonumber
hide footbox

actor "Courier" as COUR

participant "CalculateMostEfficientPahtUI" as UI
participant "CalculateMostEfficientPahtController" as CTRL
participant "ApplicationPOT" as _APP
participant "app\n:ApplicationPOT" as APP
participant "session\n:UserSession" as SESSION
participant "oDeliveryDB\n:DeliveryDB" as DELDB
participant "list\nList<Address>>" as LIST

activate COUR

COUR -> UI : Sends a request regarding what is the shortest \nand efficient path to the destiny
activate UI
UI -> CTRL : getShortestPath()
activate CTRL
CTRL -> _APP: app = getInstance()
activate _APP
deactivate _APP

CTRL -> APP: session = getCurrentSession()
activate APP
deactivate APP

CTRL -> SESSION : email = getCurrentUserEmail()
activate SESSION
deactivate SESSION

CTRL -> DELDB : list = getAddressesByDeliveryRunId(email)
activate DELDB
DELDB -> DELDB : executeQuery(query)
ref over DELDB : SD_CONNECTIONS
deactivate DELDB
CTRL -> DELDB : calculateMostEfficientPath(addressA, addressB, list)
activate DELDB
DELDB -> DELDB : executeQuery(query)
ref over DELDB : SD_CONNECTIONS
deactivate DELDB

deactivate CTRL
UI -> COUR : Shows the shortest and most efficient path, \ninforming of the success of the operation.
deactivate UI
deactivate COUR

@enduml