@startuml
autonumber
actor "Pharmacy Manager" as PHARMAN

participant ":RemoveScooterUI" as UI
participant ":RemoveScooterScooterController" as CTRL
participant "PotApplication" as PA
participant "app \n:PotApplication" as APA
participant "session \n:UserSession" as US
participant "plat \n:Platform" as PLAT
participant "pharmReg \n:PharmacyRegistration" as PH
participant "scootReg \n:ScooterRegistration" as RS



activate PHARMAN

PHARMAN -> UI : Sends a request regarding the remove of an electric scooter
activate UI
UI -> CTRL : showScootersList(pharmacy)
activate CTRL
CTRL -> PA : app = getInstance()
activate PA
deactivate PA
CTRL -> APA : plat = getPlatform()
activate APA
deactivate APA
CTRL -> APA : session = getCurrentSession()
activate APA
deactivate APA
CTRL -> US : email = getUserEmail()
activate US
deactivate US
CTRL -> PLAT : pharmReg = getPharmReg()
activate PLAT
deactivate PLAT
CTRL -> PH : pharmacy = getPharmacyByManager(email)
activate PH
ref over PH
SD_Connections
end ref
deactivate PH
CTRL -> PH : scootersList = getScootersList(pharmacy)
activate PH
ref over PH
SD_Connections
end ref
deactivate PH
deactivate CTRL
UI -> PHARMAN : Shows the list of eletric scooters and asks to choose one
deactivate UI

PHARMAN -> UI : Chooses the eletric scooter
activate UI
UI -> CTRL : removeScooter(batteryPerc, chargingStatus,\n potency, weight, batteryCapacity)
activate CTRL
CTRL -> PLAT : scootReg = getScootReg()
activate PLAT
deactivate PLAT
CTRL -> RS : removeScooter(scoot)
activate RS
RS -> RS : removeScooterFromDB(scoot)
ref over RS
SD_Connections
end ref
deactivate RS
deactivate CTRL
UI -> PHARMAN : Removes the eletric scooter

deactivate UI

deactivate PHARMAN

@enduml
