@startuml
autonumber
hide footbox

actor "Admin" as U

participant "RegisterDeliveryRunUI" as UI
participant "RegisterDeliveryRunController" as CTRL
participant "ApplicationPOT" as _APP
participant "app\n:ApplicationPOT" as APP
participant "session\n:UserSession" as SESSION

participant "pharmacyService\n:PharmacyService" as PS
participant "orderService\n:OrderService" as OS
participant "deliveryRunService\n:DeliveryRunService" as DRS
participant "pharmacyDB\n:PharmacyDB" as PDB
participant "orderDB\n:OrderDB" as ODB
participant "deliveryRunDB\n:DeliveryRunDB" as DB
participant "Address" as A
participant "deliveryRun\n:DeliveryRun" as DR
participant "status\n:DeliveryStatus" as DS


participant "DataHandler" as DH

activate U

U -> UI : Initiates the registration of a delivery run
activate UI








deactivate ODB
deactivate CTRL


UI --> U: Asks for a list of order ids

deactivate UI




U -> UI : Gives an order id list
activate UI
UI -> CTRL : registerDeliveryRun(lstOrderId)
activate CTRL
CTRL -> PS** : create()
activate PS
PS -> PDB** : create()
deactivate PS

CTRL -> OS** : create()
activate OS
OS -> ODB** : create()
deactivate OS

CTRL -> DRS** : create()
activate DRS
DRS -> DB** : create()
deactivate DRS
CTRL -> _APP: app = getInstance()
activate _APP
deactivate _APP

CTRL -> APP : session = getCurrentSession()
activate APP
deactivate APP


CTRL -> DRS : lstAddress = getAddressesFromOrdersList(lstOrderId)
activate DRS
DRS -> DB : getAddressesFromOrdersList(lstOrderId)
activate DB

ref over DB
SD_CONNECTIONS
end ref
deactivate DB
deactivate DRS



CTRL -> DRS : courier = getSuitableCourier()
activate DRS
DRS -> DB : getSuitableCourier()
activate DB
deactivate DB
deactivate DRS

ref over DB
SD_CONNECTIONS
end ref

CTRL -> DRS : lstAddress = calculateShortestPath()
activate DRS
deactivate DRS
CTRL -> DRS : deliveryRun = newDeliveryRun(courier,lstAddress)
activate DRS
DRS -> DR** : create(courier,lstAddress)
activate DR
DR -> DS** : create()
deactivate DRS



deactivate DR

CTRL -> DRS : addNewDeliveryRun(deliveryRun)
activate DRS
DRS -> DB : addNewDeliveryRun(deliveryRun)
activate DB
deactivate DRS
ref over DB
SD_CONNECTIONS
end ref
deactivate DB

CTRL -> DRS : addDelivery(lstDelivery)
activate DRS
DRS -> DB : addDelivery(lstDelivery)

activate DB
ref over DB
SD_CONNECTIONS
end ref
deactivate DB
deactivate DRS

deactivate CTRL

UI --> U : Registers the delivery run and informs\nabout the success of the operation
deactivate UI










deactivate U


@enduml