@startuml
skinparam classAttributeIconSize 0


package "Controller" #DDDDDD {
class ApplicationPOT
{
  +static getInstance()
  +getCurrentSession(session)
}
}

package "Data" #DDDDDD {
class PharmacyDB{
+getPharmacyByManagerEmail(email)
}

class OrderDB{
+getOrdersFromPharmacy(pharmacy)
}

class DeliveryRunDB {
+newDelivery(order)
+getSuitableCourier()
+addNewDeliveryRun(deliveryRun)
+addDelivery(lstDelivery)
}

class DataHandler{
+openConnection()
+closeAll()
}

}

package "UI" #DDDDDD {
class RegisterDeliveryRunUI{

}



}


package "Controller" #DDDDDD {
class RegisterDeliveryRunController{
+registerDeliveryRun(lstOrderId)
}
}


package "Model" #DDDDDD {
class Delivery{
+Delivery(order)
}

class DeliveryRun{
+DeliveryRun(courier,lstAddress)
}

}

package "Model" #DDDDDD {
class UserSession{
-String email
+getCurrentUserEmail()
}

package "Service" #DDDDDD {

class PharmacyService {
+getPharmacyByManagerEmail(email)
}

class OrderService {
+getOrdersFromPharmacy(pharmacy)
}

class DeliveryRunService {
+newDelivery(order)
+getSuitableCourier()
+newDeliveryRun(courier,lstAddress)
+addNewDeliveryRun(deliveryRun)
+addDelivery(lstDelivery)
}

}

enum DeliveryStatus{
+DeliveryStatus()
}
}






RegisterDeliveryRunUI ..> RegisterDeliveryRunController
RegisterDeliveryRunController ..> PharmacyService
RegisterDeliveryRunController ..> OrderService
RegisterDeliveryRunController ..> DeliveryRunService
RegisterDeliveryRunController ..> ApplicationPOT
PharmacyService "1" --> "1" PharmacyDB : has >
OrderService "1" --> "1" OrderDB : has >
DeliveryRunService "1" --> "1" DeliveryRunDB : has >

DeliveryRun "1" --> "*" Delivery : has
DeliveryRun "1" --> "1" DeliveryStatus : has

DeliveryRunService "1" --> "*" DeliveryRun : creates

class DeliveryRunDB extends DataHandler
class OrderDB extends DataHandler
class PharmacyDB extends DataHandler
ApplicationPOT "1" -> "1" UserSession : has

@enduml