INSERT INTO ORDERSTATUS(DESIGNATION) VALUES ('Ordered');
INSERT INTO ORDERSTATUS(DESIGNATION) VALUES ('Delivering');
INSERT INTO ORDERSTATUS(DESIGNATION) VALUES ('Delivered');


INSERT INTO DELIVERYSTATUS(DESIGNATION) VALUES ('Idle');
INSERT INTO DELIVERYSTATUS(DESIGNATION) VALUES ('InProgress');
INSERT INTO DELIVERYSTATUS(DESIGNATION) VALUES ('Finished');

INSERT INTO PARK(PHARMACYID,MAXSLOTSNUMBER) VALUES (1,10);

INSERT INTO CHARGINGSLOT(PARKPHARMACYID,SCOOTERID,OUTPUTPOWER) VALUES (1,null,200);


SELECT *
FROM CHARGINGSLOT