INSERT INTO ORDERSTATUS(DESIGNATION) VALUES ('Ordered');
INSERT INTO ORDERSTATUS(DESIGNATION) VALUES ('Delivering');
INSERT INTO ORDERSTATUS(DESIGNATION) VALUES ('Delivered');


INSERT INTO DELIVERYSTATUS(DESIGNATION) VALUES ('Idle');
INSERT INTO DELIVERYSTATUS(DESIGNATION) VALUES ('InProgress');
INSERT INTO DELIVERYSTATUS(DESIGNATION) VALUES ('Finished');
