@startuml
skinparam classAttributeIconSize 0
package "UI" #DDDDDD {
    class ProductRegistrationUI{
    }
}

package "Controller" #DDDDDD {
    class ProductRegistrationController{
        +addProduct(name,description,price)
        +updateProduct(product,name,description,price)
        +deleteProduct(name)
    }
}

package "Model" #DDDDDD {
    class Platform {
        -String designation
        +getProductReg()
    }

    class UserSession {
        +getEmailUtilizador()
    }

    class ApplicationPot {
        +static getInstance()
        +getSessaoAtual()
    }

    class Product{
        -String productId
        -String name
        -String description
        -Double price
        +save()
        +delete()
    }
}

package "Registration" #DDDDDD {
    class ProductRegistration{
        +newProduct(name,description,price)
        +validateProduct(product)
        +addProduct(product)
        +registerProduct(product)
    }
}

package "Data" #DDDDDD {
    class ProductDB{
        +getProduct(id)
        +addProduct(product)
        +addProduct(productId,name,description,price)
        +removeProduct(id)
        +updateProduct(product,name,description,price)
        +udpdateProduc(productId,name,description,price)
    }

    class DataHandler{
        -jdbcUrl
        -username
        -password
        -connection
        -callStmt
        -rSet
        +scriptRunner(fileName)
        +openConnection()
        +closeAll()
        +getConnection()
    }
}


ProductRegistrationUI ..> ProductRegistrationController
ProductRegistrationController ..> Platform
ProductRegistrationController ..> ApplicationPot
ProductRegistrationController ..> UserSession
Platform "1" -- "1" ProductRegistration: has >
ProductRegistration "1" -- "1..*" Product: Creates >
Product ..> ProductDB
ProductDB ..> DataHandler
@enduml