@startuml
skinparam classAttributeIconSize 0
hide methods
left to right direction

class Platform {
  -String strDesignation
}

class Courier {
      -Integer id
      -String iban
}

class PharmacyManager {
}


class User{
  -String email
  -String password
  -int nif
  -string name
}

class Pharmacy{
-   int id
-   String name
}

Platform "1" -- "1" PharmacyManager : has registered >
PharmacyManager "1" -- "1..*" Courier : registers >
Courier "1" -- "1" User: acts as  >
Courier "1" -- "1" Pharmacy: belongs to a  >
PharmacyManager "1" -- "1" User: acts as  >
@enduml

