@startuml
autonumber
hide footbox

actor "Courier" as COUR

participant "KnowDeliveryUI" as UI
participant "KnowDeliveryController" as CTRL
participant "ApplicationPOT" as _APP
participant "app\n:ApplicationPOT" as APP
participant "session\n:UserSession" as SESSION
participant "orderService\n:OrderService" as OS
participant "orderDB\n:OrderDB" as ODB
participant "order\n:Order" as O

activate COUR

COUR -> UI : Sends a request regarding what delivery will be done

activate UI
UI -> CTRL : getOrderByCour()
activate CTRL
CTRL -> _APP: app = getInstance()
activate _APP
deactivate _APP

CTRL -> APP: session = getCurrentSession()
activate APP
deactivate APP

CTRL -> SESSION : email = getCurrentUserEmail()
activate SESSION
deactivate SESSION

CTRL -> OS* : create()
activate OS
OS -> ODB* : create()
deactivate OS
CTRL -> OS : order = getOrderByCourier(email)
activate OS
OS -> ODB : getOrderByCourier(email)
activate ODB
deactivate ODB

ref over ODB : SD_CONNECTIONS
deactivate OS
deactivate CTRL
opt [ order == null]
UI -> COUR : Informs that doesn't exist any order
end opt
UI -> COUR : Returns the order, informing of the success of the operation
deactivate UI
deactivate COUR

@enduml