CREATE OR REPLACE PROCEDURE parkScooter(p_scooterId IN PARKINGSLOT.VEHICLEID%TYPE,
 p_parkSlotId IN PARKINGSLOT.ID%TYPE) IS
BEGIN

    UPDATE PARKINGSLOT ps
    SET VEHICLEID = p_scooterId
    WHERE ps.ID = p_parkSlotId;

end;
