@startuml
autonumber
hide footbox

actor "Administrator" as ADMIN

participant ":System" as SYST

activate ADMIN

ADMIN -> SYST : Sends a request regarding the view of an electric scooter's data
activate SYST
SYST --> ADMIN : Shows the list of eletric scooters and asks to choose one
deactivate SYST
ADMIN -> SYST : Chooses the eletric scooter
activate SYST
SYST -> ADMIN : Shows the information about the scooter

deactivate ADMIN

@enduml