@startuml
autonumber
hide footbox

actor "Admin" as ADMIN

participant ":System" as SYST

activate ADMIN

ADMIN -> SYST : Sends a request regarding the register of an electric scooter
activate SYST

SYST --> ADMIN : Shows the list of pharmacies and asks to choose one
deactivate SYST
ADMIN -> SYST : Chooses the pharmacy
activate SYST

SYST --> ADMIN : Presents the list of scooter models and asks to choose one or\ncreate a new model
deactivate SYST
alt if the admin chooses an existing model
ADMIN -> SYST : Chooses the model
activate SYST
deactivate SYST
else if the admin chooses to create a new model
ADMIN -> SYST : Chooses to create a new model
activate SYST
deactivate SYST
SYST --> ADMIN : Asks for the data that features the model (i.e., designation, potency, weight, maximum payload, battery capacity, \nbattery voltage, battery efficiency)
deactivate SYST
ADMIN -> SYST : Inserts the required data
activate SYST
end alt

SYST --> ADMIN : Shows the information about the scooter and its QR Code, requesting verification
deactivate SYST

ADMIN -> SYST : Confirms the information
activate SYST
SYST --> ADMIN : Informs the success of the operation.
deactivate SYST

deactivate ADMIN

@enduml