@startuml
skinparam classAttributeIconSize 0

database Database {
}

package "UI" #DDDDDD {
class RegisterScooterUI{
}
}

package "Controller" #DDDDDD {
class RegisterScooterController{
+getPharmacies()
+chooseVehicleModer(model)
+newVehicleModel(designation, potency, weight, maxPayload,\nbatteryCapacity, batteryVoltage, efficiency)
+newScooter(batteryPerc, potency, weight, batteryCapacity, maxPayload, pharmacy)
+registerScooter(scoot)
}
}


package "Model" #DDDDDD {
 package "Service" #DDDDDD {
  class PharmacyService{
      +PharmacyService()
      +getPharmacies()
  }

  class ScooterService{
      +ScooterService()
      +registerScooter(scoot)
   }

  class VehicleService{
      +VehicleService()
      +generateQRCode()
   }
}

package "Model" #DDDDDD {
class Park{
-   int maxSlotsNumber
-   double totalOutputCorrent
}

class ChargingSlot{
-   int id
}

class NonChargingSlot{
-   int id
}

class ParkingSlot{
-   int id
}

class Scooter{
+Scooter(batteryPerc, charginStatus, potency,\n weight, batteryCapacity, maxPayload, batteryVoltage, pharmacy)

}

class VehicleModel{
  -int id
  -String desigantion
  -double potency
  -double weight
  -double maxPayload
}

class VehicleType{
  -String desigantion
}

class Vehicle{
  -int id
  -double batteryPerc
}

class Battery{
  -int id
  -int batteryCapacity
  -double batteryVoltage
  -double efficiency
}

class Address{
  -double longitude
  -double latitude
  -String doorNumber
  -String streetName
  -String postalCode
  -String locality
  -String country
}

class Pharmacy {
  -int id
  -String name
  -String email
}
}


package "Data" #DDDDDD {
class DataHandler{
    +openConnection()
    +closeAll()
}
class PharmacyDB{
     +PharmacyDB()
     +getPharmacies()
 }

 class ScooterDB{
     +ScooterDB()
     +registerScooter(scoot)
  }

 class VehicleDB{
     +VehicleDB()
  }
}

class PharmacyDB extends DataHandler
class ScooterDB extends DataHandler
class VehicleDB extends DataHandler

RegisterScooterUI ..> RegisterScooterController
RegisterScooterController ..> PharmacyService
RegisterScooterController ..> ScooterService
RegisterScooterController ..> VehicleService

Database "1" --> "1" PharmacyDB : manages
Database "1" --> "1" ScooterDB : manages
ScooterService "1" --> "*" PharmacyDB : uses
PharmacyService "1" --> "*" ScooterDB : uses
VehicleService "1" --> "*" VehicleDB : uses
VehicleService "1" --> "*" Vehicle : manage services of
PharmacyService "1" --> "*" Pharmacy : manage services of
ScooterService "1" --> "*" Scooter : manage services of

Database "1" -- "*" Pharmacy : has registered >
Database "1" -- "*" Scooter : has registered >

Vehicle "1" -- "1" Battery : has >
Vehicle "*" -- "1" Pharmacy : belongs to a >
Scooter "*" -- "1" Vehicle : is a type of >
Vehicle "*" -- "1" VehicleModel : has >
Pharmacy "1" -- "1" Address : has >
Park "*" -- "1" VehicleType : has >
Park "1" -- "*" ParkingSlot : has >
ParkingSlot "1" -- "1" ChargingSlot : is >
ParkingSlot "1" -- "1" NonChargingSlot : is >
VehicleModel "1" -- "1" Battery : has >
VehicleModel "*" -- "1" VehicleType : has >

@enduml