@startuml
autonumber
hide footbox

actor "Admin" as U

participant ":System" as SYST

activate U

U -> SYST : Engages the "update product information" feature/button
activate SYST
SYST --> U : Asks for the for the id of the product to verify and the information to update
deactivate SYST

U -> SYST : Fills all the information required
activate SYST

SYST --> U : Validates, presents the data and asks for a confirmation
deactivate SYST

U -> SYST : Confirms
activate SYST
SYST --> U : Informs about the success of the operation
deactivate SYST


deactivate U

@enduml