CREATE OR REPLACE PROCEDURE addProduct(strName IN PRODUCT.NAME%TYPE, strDescription IN PRODUCT.DESCRIPTION%TYPE, fltUnitaryPrice IN PRODUCT.UNITARYPRICE%TYPE, fltUnitaryWeight IN PRODUCT.UNITARYWEIGHT%TYPE) IS
BEGIN

INSERT INTO PRODUCT(NAME, DESCRIPTION, UNITARYPRICE, UNITARYWEIGHT)
VALUES (strName, strDescription, fltUnitaryPrice, fltUnitaryWeight);

end;