@startuml
autonumber
actor "Admin" as ADM

activate ADM
ADM -> ":System" : wants to see the the best type of vehicle for an order
activate ":System"
":System" --> ADM : shows the best vehicle type for an order
deactivate ":System"

deactivate ADM
@enduml
