@startuml
skinparam classAttributeIconSize 0
package "UI" #DDDDDD {
    class ProductRegistrationUI{
    }
}

package "Controller" #DDDDDD {
    class RegisterProductController{
        -app
        -plat
        -pr
        +verifyString(str)
        +verifyPositiveDouble(doub)
        +verifyProductId(productId)
        +verifyProductName(productName)
        +verifyProductDescription(productDescription)
        +verifyProductUnitaryPrice(unitaryPrice)
        +verifyProductUnitaryWeight(unitaryWeight)
        +registerTask(name, description, unitaryPrice, unitaryWeight)
    }

    class UserSession {
        +getEmailUtilizador()
    }

    class ApplicationPot {
        +static getInstance()
        +getSessaoAtual()
    }
}

package "Model" #DDDDDD {
    class Platform {
        -String designation
        +getProductReg()
    }

    class Product{
        -String productId
        -String name
        -String description
        -Double unitaryPrice
        -Double unitaryWeight
    }

    package "Registration" #DDDDDD {
        class ProductRegistration{
            +registerProduct(name, description, unitaryPrice, unitaryWeight)
            +addProductToDB(p)
            +addProductToDB(name, description, unitaryPrice, unitaryWeight)
        }
    }
}


package "Data" #DDDDDD {
    class DataHandler{
        -jdbcUrl
        -username
        -password
        -connection
        -callStmt
        -rSet
        +openConnection()
        +closeAll()
    }
}


ProductRegistrationUI ..> RegisterProductController
RegisterProductController ..> Platform
RegisterProductController ..> ApplicationPot
RegisterProductController ..> UserSession
Platform "1" -- "1" ProductRegistration: has >
ProductRegistration "1" -- "1..*" Product: Creates >
class ProductRegistration extends DataHandler
@enduml