@startuml
autonumber
hide footbox

actor "Courier" as COUR

participant ":System" as SYST

activate COUR

COUR -> SYST : Sends a request regarding what delivery will be done
activate SYST
SYST -> COUR : Shows the information about the courier, requesting verification
deactivate SYST

COUR -> SYST : Verifies the information
activate SYST
SYST -> COUR : If there is any order associated to the courier, the \nsystem returns it, informing of the success of the operation.
deactivate SYST

deactivate COUR

@enduml