@startuml
skinparam classAttributeIconSize 0

class PotApplication
{
  +static getInstance()
  +getPlatform()
  +getCurrentSession()
}

class UserSession
{
  +getUserEmail()
}
class KnowDeliveryUI{

}

class KnowDeliveryController{
+getOrderByCour()
}

class Platform {
  -String designation
  +OrdersRegistry getOrdReg()
}

class OrdersRegistry{
+getOrderByCourier(email)
}


KnowDeliveryUI ..> KnowDeliveryController
KnowDeliveryController ..> Platform
KnowDeliveryController ..> PotApplication
KnowDeliveryController ..> UserSession
Platform "1" --> "1" OrdersRegistry : has
OrdersRegistry "1" --> "1" Database : connects to

@enduml