@startuml

skinparam classAttributeIconSize 0
hide attributes

note left of PasswordGeneratorAlgorithm
This interface will be a target
of multiple implementations,
one for each external algorithm
that needs to be supported.
end note

interface PasswordGeneratorAlgorithm << interface >>
{
 +String generatesPassword(String name, String email)
}


class PasswordGeneratorAlgorithmAdapter1
{
+String generatesPassword(String name, String email)
}

class ExternalAlgorithm1API
{
    +String randomPassword()
    +String randomPassword(Integer minChars, Integer maxChars)
}

PasswordGeneratorAlgorithm <|.. PasswordGeneratorAlgorithmAdapter1
PasswordGeneratorAlgorithmAdapter1 -d->  ExternalAlgorithm1API

class PasswordGeneratorAlgorithmAdapter2
{
+String generatesPassword(String name, String email)
}

class ExternalAlgorithm2API
{
    +Password generatePassword()
    +Password generatePassword(String feedChars)
    +Paswword generatePassword(Integer strength)
    +Paswword generatePassword(Integer strength, String feedChars)
}

PasswordGeneratorAlgorithm <|.. PasswordGeneratorAlgorithmAdapter2
PasswordGeneratorAlgorithmAdapter2 -d->  ExternalAlgorithm2API


@enduml