@startuml
autonumber
title UC7_SD_RegisterFreelancerAsUser
participant "frr: FreelancerRegistration" as RF
participant ":Platform" as PLAT

participant "fr: Freelancer" as FR
participant "<<interface>>\n alg: PasswordGeneratorAlgorithm" as PASS
participant "af: AuthenticationFacade" as AF

RF -> RF: RegistersFreelancerAsUser()

activate RF
RF -> FR: nome = getName()
activate FR
deactivate FR

RF -> FR: email = getEmail()
activate FR
deactivate FR

RF -> PLAT: alg=getPasswordGeneratorAlgorithm()
activate PLAT
deactivate PLAT

RF -> PASS: pwd=generatesPassword(name, email)
activate PASS
deactivate PASS

RF -> PLAT: af=getAuthenticationFacade()
activate PLAT
deactivate PLAT

RF -> AF : registersUserWithRoles(name, email, pwd, ['Freelancer'])
activate AF
deactivate AF
deactivate AF


RF -> RF : sendsEmail(nome, email, pwd)


@enduml

