@startuml
skinparam classAttributeIconSize 0
hide methods
left to right direction

class Platform {
  -String strDesignation
}

class Courier {
      -String iban
}


class User{
  -String email
  -String password
  -int nif
  -string name
}

Platform "1" -- "*" Courier : has registered >
Courier "1" -- "1" User: acts as  >
@enduml

