@startuml
skinparam classAttributeIconSize 0


class RegisterCourierUI {
    
}

class RegisterCourierController {
    
  +newCourier(id, name, email, nif, iban, address)
  +registersCourier()
}

class Platform {
  -String strDesignation
  +FreelancerRegistration getCourReg()
  +CourierDB getCourDB()
}

class CourierRegistration {

  +generateCourierId()
  +Courier newCourier(strId, strName, strEmail, strNIF, strIBAN, oAddress)
  +registersCourier(oCourier)

}

class CourierDB {
  +addCourier(courier)
}


class Courier {
    -String id
    -String name
    -String email
    -String nif
    -String iban
    -Address address

   +Courier(id, name, email, nif, iban, address)

}

class Address{
 -String streetName
   -String doorNumber
   -String locality
   -String country
   -float longitude
   -float latitude

  +PostalAddress(oAddress)

}

Platform "1" -- "1" CourierRegistration: has >

CourierRegistration "1" -- "1" CourierDB
CourierRegistration "1" -- "1" Courier : creates

RegisterCourierUI ..> RegisterCourierController

RegisterCourierController ..> Platform
RegisterCourierController ..> CourierRegistration

Courier "1" -- "1" Address: has  >

@enduml


