@startuml
skinparam classAttributeIconSize 0

left to right direction

class RegisterCourierUI {
    
}

class RegisterCourierController {
    
  +newCourier(strId, strName, strEmail, strNIF, strIBAN, oAddress)
  +registersCourier()
}

class Platform {
  -String strDesignation
  
  +FreelancerList getCourierList()
}

class CourierList {

  +generateCourierId()
  +Courier newCourier(strId, strName, strEmail, strNIF, strIBAN, oAddress)
  +registersCourier(oCourier)
  +validatesCourier(oCourier)
  -addCourier(oCourier)

  
}


class Courier {
    -String strId
          -String strName
          -String strEmail
          -String strNIF
          -String strIBAN

   +Courier(strId, strName, strEmail, strNIF, strIBAN, oAddress)

}

class Address{
 -String strStreet
   -String strDoorNum
   -String strLocality
   -String strCountry

  +PostalAddress(oAddress)

}

Platform "1" -- "1..*" CourierList: has >


RegisterCourierUI ..> RegisterCourierController

RegisterCourierController ..> Platform
RegisterCourierController ..> CourierList
RegisterCourierController ..> Courier

CourierList "1" -- "*" Courier : has registered >
Courier "1" -- "1" Address: has  >

@enduml


