@startuml
skinparam classAttributeIconSize 0
hide methods
left to right direction

class Platform {
  -String strDesignation
}

class Courier {
      -Integer id
      -String iban
}

class Administator {
      -Integer id
}


class User{
  -String email
  -String password
  -int nif
  -string name
}

Platform "1" -- "1" Administator : has registered >
Administator "1" -- "1..*" Courier : registers >
Courier "1" -- "1" User: acts as  >
Administator "1" -- "1" User: acts as  >
@enduml

