@startuml
skinparam classAttributeIconSize 0
hide methods
left to right direction

class Platform {
  -String designation
}

class Pharmacy {
  -int id
  -String name
}

class Scooter{
  -int id
  -int batteryPerc
  -int charginStatus
  -int potency
  -int weight
  -int batteryCapacity
}

class Address{
  -float longitude
  -float latitude
  -String doorNumber
  -String streetName
  -String postalCode
  -String locality
  -String country
}



Platform "1" -- "*" Pharmacy : has >
Pharmacy "1" -- "*" Scooter : has registered >
Pharmacy "1" -- "1" Address : has >
@enduml

