@startuml
autonumber
actor "Administrator" as ADMIN

participant ":RegisterScooterUI" as UI
participant ":RegisterScooterController" as CTRL
participant "PotApplication" as PA
participant "app \n:PotApplication" as APA
participant "session \n:UserSession" as US
participant "plat \n:Platform" as PLAT
participant "pharmReg \n:PharmacyRegistration" as PH
participant "scootReg \n:ScooterRegistration" as RS
participant "scoot: Scooter" as SC



activate ADMIN

ADMIN -> UI : initializes the register of a new scooter
activate UI
UI -> ADMIN : asks for the data that features the scooter (i.e., battery, \nbattery capacity, maximum weight, pharmacy id, status, potency)
deactivate UI

ADMIN -> UI : inserts the required data
activate UI
UI -> CTRL : newScooter(maxWeight, battery,\n batteryCapacity, status, potency, pharmacyId)
activate CTRL
CTRL -> PA : app = getInstance()
activate PA
deactivate PA
CTRL -> APA : plat = getPlatform()
activate APA
deactivate APA
CTRL -> APA : session = getCurrentSession()
activate APA
deactivate APA
CTRL -> US : email = getUserEmail()
activate US
deactivate US
CTRL -> PLAT : pharmReg = getPharmReg()
activate PLAT
deactivate PLAT
CTRL -> PH : pharmacy = getPharmacyById(pharmacyId)
activate PH
PH -> PH : getConnection()
ref over PH
SD_connectionDataBase
end ref
deactivate PH
CTRL -> PLAT : scootReg = getScootReg()
activate PLAT
deactivate PLAT
CTRL -> RS : newScooter(maxWeight, battery, batteryCapacity, status, potency, pharmacyId)
activate RS
RS -> SC ** : create(maxWeight, battery,\nbatteryCapacity, status, potency, pharmacyId)
RS -> RS : validateScooter(scoot)
deactivate RS
deactivate CTRL


UI -> ADMIN : validates, presents the data and asks for a confirmation
deactivate UI

ADMIN -> UI : confirms
activate UI
UI -> CTRL : registersScooter()
activate CTRL
CTRL -> RS : registersScooter(scooter)
activate RS
RS -> RS : getConnection()
ref over RS
SD_connectionDataBase
end ref
deactivate RS
deactivate CTRL
UI -> ADMIN : informs the success of the operation
deactivate UI

deactivate ADMIN

@enduml
