@startuml
autonumber
hide footbox

actor "Pharmacy Manager" as PHARMAN

participant ":System" as SYST

activate PHARMAN

PHARMAN -> SYST : Sends a request regarding the register of an electric scooter
activate SYST
SYST --> PHARMAN : Asks for the data that features the electric scooter (i.e., battery, \nbattery capacity, maximum Weight, pharmacy id, status, potency)
deactivate SYST

PHARMAN -> SYST : Inserts the required data
activate SYST
SYST -> PHARMAN : Shows the information about the scooter, requesting verification
deactivate SYST

PHARMAN -> SYST : Confirms the information
activate SYST
SYST -> PHARMAN : Informs the success of the operation.
deactivate SYST

deactivate PHARMAN

@enduml