@startuml
autonumber
actor "Pharmacy Manager" as PHARMAN

participant ":RegisterScooterUI" as UI
participant ":RegisterScooterController" as CTRL
participant "PotApplication" as PA
participant "app \n:PotApplication" as APA
participant "session \n:UserSession" as US
participant "plat \n:Platform" as PLAT
participant "pharmReg \n:PharmacyRegistration" as PH
participant "scootReg \n:ScooterRegistration" as RS
participant "scoot: Scooter" as SC



activate PHARMAN

PHARMAN -> UI : initializes the register of a new scooter
activate UI
UI -> PHARMAN : asks for the data that features the scooter (i.e., battery, \nbattery capacity, maximum weight, pharmacy, status, potency)
deactivate UI

PHARMAN -> UI : inserts the required data
activate UI
UI -> CTRL : newScooter(batteryPerc, chargingStatus,\n potency, weight, batteryCapacity, pharmacy)
activate CTRL
CTRL -> PA : app = getInstance()
activate PA
deactivate PA
CTRL -> APA : plat = getPlatform()
activate APA
deactivate APA
CTRL -> APA : session = getCurrentSession()
activate APA
deactivate APA
CTRL -> US : email = getUserEmail()
activate US
deactivate US
CTRL -> PLAT : pharmReg = getPharmReg()
activate PLAT
deactivate PLAT
CTRL -> PH : pharmacy = getPharmacyByManager(email)
activate PH
ref over PH
SD_Connections
end ref
deactivate PH
CTRL -> PLAT : scootReg = getScootReg()
activate PLAT
deactivate PLAT
CTRL -> RS : newScooter(batteryPerc, chargingStatus,\n potency, weight, batteryCapacity, pharmacy)
activate RS
RS -> SC ** : create(batteryPerc, chargingStatus,\n potency, weight, batteryCapacity, pharmacy)
RS -> RS : validateScooter(scoot)
ref over RS
SD_Connections
end ref
deactivate RS
deactivate CTRL


UI -> PHARMAN : validates, presents the data and asks for a confirmation
deactivate UI

PHARMAN -> UI : confirms
activate UI
UI -> CTRL : registersScooter()
activate CTRL
CTRL -> RS : registersScooter(scooter)
activate RS
ref over RS
SD_Connections
end ref
deactivate RS
deactivate CTRL
UI -> PHARMAN : informs the success of the operation
deactivate UI

deactivate PHARMAN

@enduml
