@startuml
skinparam classAttributeIconSize 0
hide methods
left to right direction

database Database {
}

class Pharmacy {
  -int id
  -String name
-   String email
}

class Park{
-   int maxSlotsNumber
-   double totalOutputCorrent
}

class ChargingSlot{
-   int id
}

class NonChargingSlot{
-   int id
}

class ParkingSlot{
-   int id
}

class Scooter{
}

class VehicleModel{
  -int id
  -String desigantion
  -double potency
  -double weight
  -double maxPayload
}

class VehicleType{
  -String desigantion
}

class Vehicle{
  -int id
  -double batteryPerc
}

class Battery{
  -int id
  -int batteryCapacity
  -double batteryVoltage
  -double efficiency
}

class Address{
  -double longitude
  -double latitude
  -double altitude
  -String doorNumber
  -String streetName
  -String postalCode
  -String locality
  -String country
}



Database "1" -- "*" Pharmacy : has >
Database "1" -- "*" Scooter : has >
Scooter "*" -- "1" Vehicle : is a type of >
Vehicle "*" -- "1" VehicleModel : has >
Vehicle "*" -- "1" Pharmacy : belongs to a >
Pharmacy "1" -- "1" Address : has >
Pharmacy "1" -- "*" Park : has >
Park "*" -- "1" VehicleType : has >
Park "1" -- "*" ParkingSlot : has >
ParkingSlot "1" -- "1" ChargingSlot : is >
ParkingSlot "1" -- "1" NonChargingSlot : is >
VehicleModel "1" -- "1" Battery : has >
VehicleModel "*" -- "1" VehicleType : has >
@enduml

