@startuml
autonumber
hide footbox

actor "Courier" as COUR

participant "CalculateMostEfficientPahtUI" as UI
participant "CalculateMostEfficientPahtController" as CTRL
participant "ApplicationPOT" as _APP
participant "app\n:ApplicationPOT" as APP
participant "session\n:UserSession" as SESSION
participant "plat\n:Platform" as PLAT
participant "ordReg\n:OrderRegistration" as ORDREG
participant "delReg\n:DeliveryRegistration" as DELREG
participant "pairAddress\nPair<Address, Address>" as PAIR

activate COUR

COUR -> UI : Sends a request regarding what is the shortest \nand efficient path to the destiny
activate UI
UI -> CTRL : getShortestPath()
activate CTRL
CTRL -> _APP: app = getInstance()
activate _APP
deactivate _APP

CTRL -> APP: plat = getPlaform()
activate APP
deactivate APP
CTRL -> APP: session = getCurrentSession()
activate APP
deactivate APP

CTRL -> SESSION : email = getCurrentUserEmail()
activate SESSION
deactivate SESSION

CTRL -> PLAT : delReg = getDelReg()

activate PLAT
deactivate PLAT

CTRL -> PLAT : ordReg = getOrderReg()

activate PLAT
deactivate PLAT

CTRL -> ORDREG : order = getOrderByCourier(email)
activate ORDREG
ORDREG -> ORDREG : executeQuery(query)
ref over ORDREG : SD_CONNECTIONS
deactivate ORDREG
CTRL -> DELREG : pairAddress = getStartingAndDeliveryAddressByOrder(order)
activate DELREG
DELREG -> DELREG : executeQuery(query)
ref over DELREG : SD_CONNECTIONS
deactivate DELREG
CTRL -> DELREG : getShortestPath(pairAddress)
activate DELREG
deactivate DELREG
deactivate CTRL
UI -> COUR : Shows the shortest and most efficient path, \ninforming of the success of the operation.
deactivate UI
deactivate COUR

@enduml