@startuml
autonumber
actor "Client" as Client

participant ":NotifyAndRemoveUI" as UI
participant ":NotifyAndRemoveController" as CTRL
participant "orderService \n:OrderService" as ORDERSV
participant "orderReg \n:OrderDB" as RF


activate Client

Client -> UI : makes an order
alt if order cannot be entirely fulfilled
activate UI
UI -> CTRL : notifyAndRemove(order)
activate CTRL
CTRL -> ORDERSV** :create()
activate ORDERSV
ORDERSV -> RF** : create()
deactivate ORDERSV
CTRL -> ORDERSV : notifyAndRemove(order)
activate ORDERSV
ORDERSV -> RF : notifyAndRemove(order)
ref over RF : SD_CONNECTIONS
activate RF
deactivate ORDERSV
deactivate RF
deactivate CTRL


UI -> Client : notifies the Client of the unsuccessful operation
deactivate UI
end
deactivate Client

@enduml
