DROP TABLE Address CASCADE CONSTRAINTS;
DROP TABLE Administrator CASCADE CONSTRAINTS;
DROP TABLE ChargingSlot CASCADE CONSTRAINTS;
DROP TABLE Client CASCADE CONSTRAINTS;
DROP TABLE Consumption CASCADE CONSTRAINTS;
DROP TABLE Courier CASCADE CONSTRAINTS;
DROP TABLE Delivery CASCADE CONSTRAINTS;
DROP TABLE DeliveryRun CASCADE CONSTRAINTS;
DROP TABLE Invoice CASCADE CONSTRAINTS;
DROP TABLE InvoiceLine CASCADE CONSTRAINTS;
DROP TABLE "Order" CASCADE CONSTRAINTS;
DROP TABLE Order_Product CASCADE CONSTRAINTS;
DROP TABLE Park CASCADE CONSTRAINTS;
DROP TABLE ParkingSlot CASCADE CONSTRAINTS;
DROP TABLE Pharmacy CASCADE CONSTRAINTS;
DROP TABLE Pharmacy_Product CASCADE CONSTRAINTS;
DROP TABLE Product CASCADE CONSTRAINTS;
DROP TABLE Scooter CASCADE CONSTRAINTS;
DROP TABLE Status CASCADE CONSTRAINTS;
DROP TABLE "User" CASCADE CONSTRAINTS;


CREATE TABLE Address (id number(10) GENERATED AS IDENTITY, latitude float(10) NOT NULL, longitude float(10) NOT NULL, doorNumber varchar2(255) NOT NULL, streetName varchar2(255) NOT NULL, postalCode varchar2(255) NOT NULL, locality varchar2(255) NOT NULL, country varchar2(255) NOT NULL, PRIMARY KEY (id));
CREATE TABLE Administrator (Userid number(10) NOT NULL, nif number(10), PRIMARY KEY (Userid));
CREATE TABLE ChargingSlot (id number(10) GENERATED AS IDENTITY, ParkPharmacyid number(10) NOT NULL, Scooterid number(10) UNIQUE, outputPower float(10) NOT NULL, PRIMARY KEY (id));
CREATE TABLE Client (Userid number(10) NOT NULL, name varchar2(255) NOT NULL, nif int, cardNumber number(10), credits number(10), Invoiceid number(10) NOT NULL, Addressid number(10) NOT NULL, PRIMARY KEY (Userid));
CREATE TABLE Consumption (id number(10) GENERATED AS IDENTITY, Orderid number(10) NOT NULL, PRIMARY KEY (id));
CREATE TABLE Courier (Userid number(10) NOT NULL, name varchar2(255), nif double precision, iban varchar2(255), PRIMARY KEY (Userid));
CREATE TABLE Delivery (Orderid number(10) NOT NULL, deliveryDate date, notes varchar2(255), DeliveryRunid number(10) NOT NULL, PRIMARY KEY (Orderid));
CREATE TABLE DeliveryRun (id number(10) GENERATED AS IDENTITY, CourierUserid number(10) NOT NULL, DeliveryOrderid number(10) NOT NULL, Scooterid number(10) NOT NULL, status number(10), PRIMARY KEY (id));
CREATE TABLE Invoice (id number(10) GENERATED AS IDENTITY, Orderid number(10) NOT NULL UNIQUE, invoiceDate date, totalPrice float(10), ClientUserid number(10) NOT NULL, PRIMARY KEY (id));
CREATE TABLE InvoiceLine (Invoiceid number(10) NOT NULL, id number(10) NOT NULL, Order_Productid number(10) NOT NULL, Order_ProductConsumptionid number(10), value float(10), PRIMARY KEY (Invoiceid, id));
CREATE TABLE "Order" (id number(10) GENERATED AS IDENTITY, ClientUserid number(10) NOT NULL, Statusdesignation varchar2(255) NOT NULL, totalWeight float(10) NOT NULL, orderDate date, description varchar2(255), additionalFee float(10), PRIMARY KEY (id));
CREATE TABLE Order_Product (Consumptionid number(10) NOT NULL, id number(10) NOT NULL, Productid number(10) NOT NULL, quantity number(10) NOT NULL, unitaryPrice float(10), PRIMARY KEY (Consumptionid, id));
CREATE TABLE Park (Pharmacyid number(10) NOT NULL, maxSlotsNumber number(10), PRIMARY KEY (Pharmacyid));
CREATE TABLE ParkingSlot (ParkPharmacyid number(10), Scooterid number(10) UNIQUE);
CREATE TABLE Pharmacy (id number(10) GENERATED AS IDENTITY, name varchar2(255), "parking slot" number(10), "charging slot" number(10), Addressid number(10) NOT NULL, PRIMARY KEY (id));
CREATE TABLE Pharmacy_Product (Pharmacyid number(10) NOT NULL, Productid number(10) NOT NULL, stock number(10), ProductunitaryPrice float(10) NOT NULL, PRIMARY KEY (Pharmacyid, Productid, ProductunitaryPrice));
CREATE TABLE Product (id number(10) GENERATED AS IDENTITY, name varchar2(255), description varchar2(255), unitaryPrice float(10) NOT NULL, unitaryWeight float(10), PRIMARY KEY (id));
CREATE TABLE Scooter (id number(10) GENERATED AS IDENTITY, batteryPerc number(10), chargingStatus number(10), potency number(10), weight number(10), batteryCapacity number(10), PRIMARY KEY (id));
CREATE TABLE Status (designation varchar2(255) NOT NULL, PRIMARY KEY (designation));
CREATE TABLE "User" (id number(10) GENERATED AS IDENTITY, email varchar2(255) NOT NULL UNIQUE, password varchar2(255) NOT NULL, PRIMARY KEY (id));

ALTER TABLE Courier ADD CONSTRAINT FKCourier80002 FOREIGN KEY (Userid) REFERENCES "User" (id);
ALTER TABLE Client ADD CONSTRAINT FKClient608902 FOREIGN KEY (Userid) REFERENCES "User" (id);
ALTER TABLE Client ADD CONSTRAINT FKClient632554 FOREIGN KEY (Addressid) REFERENCES Address (id);
ALTER TABLE "Order" ADD CONSTRAINT FKOrder929682 FOREIGN KEY (ClientUserid) REFERENCES Client (Userid);
ALTER TABLE Administrator ADD CONSTRAINT FKAdministra783305 FOREIGN KEY (Userid) REFERENCES "User" (id);
ALTER TABLE InvoiceLine ADD CONSTRAINT FKInvoiceLin28481 FOREIGN KEY (Invoiceid) REFERENCES Invoice (id);
ALTER TABLE Pharmacy ADD CONSTRAINT FKPharmacy139496 FOREIGN KEY (Addressid) REFERENCES Address (id);
ALTER TABLE "Order" ADD CONSTRAINT FKOrder686984 FOREIGN KEY (Statusdesignation) REFERENCES Status (designation);
ALTER TABLE Pharmacy_Product ADD CONSTRAINT FKPharmacy_P819144 FOREIGN KEY (Pharmacyid) REFERENCES Pharmacy (id);
ALTER TABLE Pharmacy_Product ADD CONSTRAINT FKPharmacy_P411453 FOREIGN KEY (Productid) REFERENCES Product (id);
ALTER TABLE Park ADD CONSTRAINT FKPark427298 FOREIGN KEY (Pharmacyid) REFERENCES Pharmacy (id);
ALTER TABLE ParkingSlot ADD CONSTRAINT FKParkingSlo446852 FOREIGN KEY (ParkPharmacyid) REFERENCES Park (Pharmacyid);
ALTER TABLE ChargingSlot ADD CONSTRAINT FKChargingSl589529 FOREIGN KEY (ParkPharmacyid) REFERENCES Park (Pharmacyid);
ALTER TABLE ChargingSlot ADD CONSTRAINT FKChargingSl323330 FOREIGN KEY (Scooterid) REFERENCES Scooter (id);
ALTER TABLE ParkingSlot ADD CONSTRAINT FKParkingSlo819346 FOREIGN KEY (Scooterid) REFERENCES Scooter (id);
ALTER TABLE Delivery ADD CONSTRAINT FKDelivery113460 FOREIGN KEY (Orderid) REFERENCES "Order" (id);
ALTER TABLE DeliveryRun ADD CONSTRAINT FKDeliveryRu967119 FOREIGN KEY (CourierUserid) REFERENCES Courier (Userid);
ALTER TABLE DeliveryRun ADD CONSTRAINT FKDeliveryRu904364 FOREIGN KEY (Scooterid) REFERENCES Scooter (id);
ALTER TABLE Delivery ADD CONSTRAINT FKDelivery346255 FOREIGN KEY (DeliveryRunid) REFERENCES DeliveryRun (id);
ALTER TABLE Invoice ADD CONSTRAINT FKInvoice114281 FOREIGN KEY (Orderid) REFERENCES "Order" (id);
ALTER TABLE Order_Product ADD CONSTRAINT FKOrder_Prod598523 FOREIGN KEY (Productid) REFERENCES Product (id);
ALTER TABLE InvoiceLine ADD CONSTRAINT FKInvoiceLin528679 FOREIGN KEY (Order_ProductConsumptionid, Order_Productid) REFERENCES Order_Product (Consumptionid, id);
ALTER TABLE Invoice ADD CONSTRAINT FKInvoice499166 FOREIGN KEY (ClientUserid) REFERENCES Client (Userid);
ALTER TABLE Consumption ADD CONSTRAINT FKConsumptio700822 FOREIGN KEY (Orderid) REFERENCES "Order" (id);
ALTER TABLE Order_Product ADD CONSTRAINT FKOrder_Prod82340 FOREIGN KEY (Consumptionid) REFERENCES Consumption (id);
