@startuml
skinparam classAttributeIconSize 0
hide methods
left to right direction

database Database {
}

class Client{
-   int IBAN
-   long creditCardNumber
-   int validityDate
-   int CCV
}

class User{
-   int id
-   String name
-   String email
-   String password
-   Integer nif
}

class Address{
-   int id
-   String streetName
-   String doorNumber
-   String postalCode
-   String locality
-   String country
-   float longitude
-   float latitude
}

class Order{
-   int id
-   float amount
-   float totalWeight
-   float additionalFee
-   Date orderDate
-   String description
-   String status
-   boolean isHomeDelivery
}

class Product{
-   int id
-   String name
-   String description
-   float unitaryPrice
-   float unitaryWeight
}

class Pharmacy{
-   int id
-   String name
}

class CreditCard{
-   int id
-   Long creditCardNr
-   String validityDate
-   Integer CCV
}

class Payment{
-   float value
}

class Invoice{
-   int id
-   Date orderDate
-   float totalAmount
}

Database "1" -- "*" Client : has registered >
Database "1" -- "*" Order : has registered >
Database "1" -- "*" Product : has registered >
Database "1" -- "*" Address : has registered >
Database "1" -- "*" CreditCard : has registered >
Database "1" -- "*" Payment : has registered >
Database "1" -- "*" Invoice : has registered >
Order "1" -- "*" Product : has >
Order "1" -- "*" Pharmacy : has >
Client "0..1" -- "1" User: acts as >
Client "1" -- "1" Order : makes >
Client "1" -- "1" Address : has >
Pharmacy "1" -- "1" Address : has >
Client "*" -- "*" CreditCard : has >
Payment "*" -- "1" CreditCard : has >
Invoice "1" -- "*" Payment : has >
Invoice "1" -- "*" Product : has >
Invoice "1" -- "1" Order : has >
Invoice "1" -- "1" Client : has >
@enduml