@startuml
autonumber
hide footbox

actor "Client" as CL

participant "MakeAnOrderUI" as UI
participant "MakeAnOrderController" as CTRL
participant "PotApplication" as _APP
participant "app\n:PotApplication" as APP
participant "session\n:UserSession" as SESSION
participant "clientServ\n:ClientService" as CS
participant "clientDB\n:ClientDB" as CDB
participant "pharmacyServ\n:PharmacyService" as PHS
participant "pharmacyDB\n:PharmacyDB" as PHDB
participant "productServ\n:ProductService" as PS
participant "productDB\n:ProductDB" as PDB
participant "orderServ\n:OrderService" as OS
participant "orderDB\n:OrderDB" as ODB
participant "order\n:Order" as O
participant "address\n:Address" as AD
participant "client\n:Client" as C

activate CL

CL -> UI : sends a request to make an order
activate UI
UI -> CTRL : lstPharmacies = getPharmacies()
activate CTRL
CTRL -> _APP: app = getInstance()
activate _APP
deactivate _APP

CTRL -> APP: session = getCurrentSession()
activate APP
deactivate APP

CTRL -> SESSION: email = getUserEmail()
activate SESSION
deactivate SESSION
CTRL -> CS** : create()
activate CS
CS -> CDB** : create()
deactivate CS
CTRL -> CDB : client = getUserByEmail(email)
activate CDB
ref over CDB
SD_CONNECTIONS
end ref
deactivate CDB
CTRL -> PHS** : create()
activate PHS
PHS -> PHDB** : create()
deactivate PHS
CTRL -> PHS : lstPharmacies = getPharmacies()
activate PHS
PHS -> PHDB : lstPharmacies = getPharmacies()
activate PHDB
ref over PHDB
SD_CONNECTIONS
end ref
deactivate PHDB
deactivate PHS
deactivate CTRL

UI -> CL : shows the list of the pharmacies
deactivate UI

CL -> UI : chooses which products and which quantities to order
activate UI
UI -> CTRL : lstProducts = getAvailableProducts(pharmacy)
activate CTRL
CTRL -> PS** : create()
activate PS
PS -> PDB** : create()
deactivate PS
CTRL -> PS : lstProducts = getAvailableProducts()
activate PS
PS -> PDB : lstProducts = getAvailableProducts()
activate PDB
ref over PDB
SD_CONNECTIONS
end ref
deactivate PDB
deactivate PS
deactivate CTRL
loop until there is no more products to add
UI -> CL : shows the list of the available products
deactivate UI

CL -> UI : chooses which product and which quantity to order
activate UI
UI -> CTRL : addProductToOrder(product, quantity)
activate CTRL
deactivate CTRL
UI -> CL : asks if the user is done adding more products
deactivate UI
end

CL -> UI : confirms that there is not more products
activate UI
UI -> CTRL : newOrder(address, amount, additionalFee,\n dateOrder, description)
activate CTRL

CTRL -> OS** : create()
activate OS
OS -> ODB** : create()
deactivate OS
CTRL -> OS : order = addOrder(amount, additionalFee, dateOrder, description, mapProducts, client, streetName,doorNumber,locality,country,longitude,longitude)
activate OS
OS -> O** : create(amount, additionalFee, dateOrder, description, mapProducts, client, streetName,doorNumber,locality,country,longitude,longitude)
activate O
O -> AD** : create(streetName,doorNumber,locality,country,longitude,longitude)
O -> C : addCredits(addtionalCredits)
activate C
deactivate C
deactivate O
deactivate OS
deactivate CTRL
UI -> CL : validates, presents the order and asks for a confirmation
deactivate UI

CL -> UI : confirms
activate UI
UI -> CTRL : registerOrder()
activate CTRL
CTRL -> OS : registerOrder(order)
activate OS
OS -> ODB : registerOrder(order)
activate ODB
ref over ODB
SD_CONNECTIONS
end ref
deactivate ODB
deactivate OS
deactivate CTRL
UI -> CL : registers the order, generates the invoice\n and informs of the success of the operation
deactivate UI
deactivate CL

@enduml