@startuml
autonumber
hide footbox

actor "Client" as CL
participant ":System" as SYST

activate CL

CL -> SYST : sends a request to make an order
activate SYST
SYST --> CL : shows the list of pharmacies
deactivate SYST

CL -> SYST : chooses the pharmacy
activate SYST
loop until there is no more products to add
SYST --> CL : shows the list of the available products of said pharmacy
deactivate SYST

CL -> SYST : chooses which product and which quantity to order
activate SYST
SYST --> CL : asks if the user is done adding more products
deactivate SYST
end

CL -> SYST : confirms that there is not more products
activate SYST

SYST --> CL : registers the order, generates the invoice\n and informs of the success of the operation

deactivate SYST

deactivate CL

@enduml