@startuml
autonumber
hide footbox

actor "Client" as CL

participant "MakeAnOrderUI" as UI
participant "MakeAnOrderController" as CTRL
participant "PotApplication" as _APP
participant "app\n:PotApplication" as APP
participant "session\n:UserSession" as SESSION
participant "plat\n:Platform" as PLAT
participant "clientReg\n:ClientRegistration" as CR
participant "pharmacyReg\n:PharmacyRegistration" as PHR
participant "prodReg\n:ProductRegistration" as PR
participant "orderReg\n:OrderRegistration" as OR
participant "order\n:Order" as O
participant "address\n:Address" as AD
participant "client\n:Client" as C

activate CL

CL -> UI : sends a request to make an order
activate UI
UI -> CTRL : lstPharmacies = getPharmacies()
activate CTRL
CTRL -> _APP: app = getInstance()
activate _APP
deactivate _APP

CTRL -> APP: plat = getPlaform()
activate APP
deactivate APP

CTRL -> APP: session = getCurrentSession()
activate APP
deactivate APP

CTRL -> SESSION: email = getUserEmail()
activate SESSION
deactivate SESSION
CTRL -> PLAT : clienteReg = getClientReg()
activate PLAT
deactivate PLAT
CTRL -> CR : client = getUserByEmail(email)
activate CR
ref over CR
SD_CONNECTIONS
end ref
deactivate CR
CTRL -> PLAT : pharmacyReg = getPharmacyReg()
activate PLAT
deactivate PLAT
CTRL -> PHR : lstPharmacies = getPharmacies()
activate PHR
ref over PHR
SD_CONNECTIONS
end ref
deactivate PHR
deactivate CTRL

UI -> CL : shows the list of the pharmacies
deactivate UI

CL -> UI : chooses which products and which quantities to order
activate UI
UI -> CTRL : lstProducts = getAvailableProducts(pharmacy)
activate CTRL
CTRL -> PLAT : prodReg = getProductReg()
activate PLAT
deactivate PLAT
CTRL -> PR : lstProducts = getAvailableProducts()
activate PR
ref over PR
SD_CONNECTIONS
end ref
deactivate PR
deactivate CTRL
loop until there is no more products to add
UI -> CL : shows the list of the available products
deactivate UI

CL -> UI : chooses which product and which quantity to order
activate UI
UI -> CTRL : addProductToOrder(product, quantity)
activate CTRL
deactivate CTRL
UI -> CL : asks if the user is done adding more products
deactivate UI
end

CL -> UI : confirms that there is not more products
activate UI
UI -> CTRL : newOrder(address, amount, additionalFee, dateOrder, description, mapProducts)
activate CTRL
CTRL -> PLAT : ordReg = getOrderReg()
activate PLAT
deactivate PLAT
CTRL -> OR : order = addOrder(amount, additionalFee, dateOrder, description, mapProducts, client, streetName,doorNumber,locality,country,longitude,longitude)
activate OR
OR -> O** : create(amount, additionalFee, dateOrder, description, mapProducts, client, streetName,doorNumber,locality,country,longitude,longitude)
activate O
O -> AD** : create(streetName,doorNumber,locality,country,longitude,longitude)
O -> C** : addCredits(addtionalCredits)
deactivate O
OR -> OR : validateOrder(order)
ref over OR
SD_CONNECTIONS
end ref
deactivate OR
deactivate CTRL
UI -> CL : validates, presents the order and asks for a confirmation
deactivate UI

CL -> UI : confirms
activate UI
UI -> CTRL : registerOrder()
activate CTRL
CTRL -> OR : registerOrder(order)
activate OR
ref over OR
SD_CONNECTIONS
end ref
deactivate OR
deactivate CTRL
UI -> CL : registers the order and informs of the success of the operation
deactivate UI
deactivate CL

@enduml